import type { Lang, Reference, Service } from './types'

/* Order = business priority: automation, AI and integrations lead (core
   focus), then web / apps / mobile / desktop. Colors are positional — they
   keep the deck's smooth teal→pink ramp regardless of service order. */
export const SERVICES: Service[] = [
  {
    id: 'automation', index: '01', color: '#45F0D8',
    cs: { name: 'Automatizace', tagline: 'Ruční práci uděláme jednou — kódem.', points: ['Workflow & skripty', 'Reporting & scraping', 'Úspora hodin týdně'] },
    en: { name: 'Automation', tagline: 'Manual work, done once — in code.', points: ['Workflows & scripts', 'Reporting & scraping', 'Hours saved weekly'] },
  },
  {
    id: 'ai', index: '02', color: '#4FC8F0',
    cs: { name: 'AI integrace', tagline: 'LLM ve vašich procesech — užitečně, ne na efekt.', points: ['Claude / GPT integrace', 'RAG & vlastní data', 'Vyhodnotitelné výstupy'] },
    en: { name: 'AI integration', tagline: 'LLMs in your workflows — useful, not flashy.', points: ['Claude / GPT integration', 'RAG & your data', 'Measurable output'] },
  },
  {
    id: 'api', index: '03', color: '#6FA8FF',
    cs: { name: 'API & integrace', tagline: 'Systémy, které spolu mluví.', points: ['REST / GraphQL', 'Platby, ERP, CRM', 'Dokumentace samozřejmostí'] },
    en: { name: 'APIs & integrations', tagline: 'Systems that talk to each other.', points: ['REST / GraphQL', 'Payments, ERP, CRM', 'Documented by default'] },
  },
  {
    id: 'web', index: '04', color: '#8F8AFF',
    cs: { name: 'Webové stránky', tagline: 'Prezentační weby, které si lidé zapamatují.', points: ['Next.js / Astro', 'WebGL & motion design', 'SEO od základu'] },
    en: { name: 'Websites', tagline: 'Websites people remember.', points: ['Next.js / Astro', 'WebGL & motion design', 'SEO by default'] },
  },
  {
    id: 'webapps', index: '05', color: '#B07CFF',
    cs: { name: 'Webové aplikace', tagline: 'Od interních nástrojů po SaaS produkty.', points: ['React / Next.js', 'Realtime & dashboardy', 'Škálovatelná architektura'] },
    en: { name: 'Web apps', tagline: 'From internal tools to SaaS products.', points: ['React / Next.js', 'Realtime & dashboards', 'Architecture that scales'] },
  },
  {
    id: 'mobile', index: '06', color: '#E06CF0',
    cs: { name: 'Mobilní aplikace', tagline: 'iOS i Android z jedné codebase.', points: ['React Native / Expo', 'Nativní výkon', 'App Store & Play release'] },
    en: { name: 'Mobile apps', tagline: 'iOS and Android from one codebase.', points: ['React Native / Expo', 'Native performance', 'App Store & Play release'] },
  },
  {
    id: 'desktop', index: '07', color: '#FF6FB3',
    cs: { name: 'Desktopové aplikace', tagline: 'Nástroje pro Windows, macOS i Linux.', points: ['Electron / Tauri', 'Offline-first', 'Auto-update pipeline'] },
    en: { name: 'Desktop apps', tagline: 'Tools for Windows, macOS and Linux.', points: ['Electron / Tauri', 'Offline-first', 'Auto-update pipeline'] },
  },
]

export const REFERENCES: Reference[] = [
  {
    id: 'jepostaveno', index: '01', color: '#88C819',
    url: 'https://www.jepostaveno.cz', domain: 'jepostaveno.cz',
    assets: { desktop: '/assets/refs/jepostaveno-desktop.jpg', mobile: '/assets/refs/jepostaveno-mobile.jpg' },
    cs: { name: 'Je Postaveno', tagline: 'Stavební portál s články, katalogem ověřených firem a poradnou.', points: ['Redakce, seriály & komunita', 'Katalog ověřených firem', 'AI asistent v poradně'] },
    en: { name: 'Je Postaveno', tagline: 'A construction portal with articles, a verified-company directory and an advisory section.', points: ['Editorial, series & community', 'Verified-company directory', 'AI assistant in the Q&A'] },
  },
  {
    id: 'izolacefuk', index: '02', color: '#84CC16',
    url: 'https://www.izolacefuk.cz', domain: 'izolacefuk.cz',
    assets: { desktop: '/assets/refs/izolacefuk-desktop.jpg', mobile: '/assets/refs/izolacefuk-mobile.jpg' },
    cs: { name: 'Izolace FUK', tagline: 'Prezentační web s galerií realizací a poptávkovým formulářem pro izolační firmu.', points: ['Galerie realizací', 'Poptávkový formulář', '4 000+ realizací · celá ČR'] },
    en: { name: 'Izolace FUK', tagline: 'A marketing site with a project gallery and lead-inquiry form for an insulation contractor.', points: ['Project gallery', 'Lead-inquiry form', '4,000+ projects nationwide'] },
  },
]

export const COPY = {
  cs: {
    meta: {
      title: 'HALF — Software studio | Weby, aplikace, AI',
      description: 'Stavíme weby, webové i mobilní aplikace, API, desktopové programy, AI integrace a automatizace. Weby připravené na AI vyhledávání. Druhá polovina vašeho nápadu.',
    },
    nav: { services: 'Služby', references: 'Reference', about: 'Studio', demo: 'Demo zdarma', contact: 'Kontakt', lang: 'EN', langHref: '/en' },
    hero: {
      kicker: 'Software studio',
      headline: 'Druhá polovina vašeho nápadu.',
      sub: 'Weby, aplikace a AI integrace. Od první konzultace po nasazení a provoz.',
      scrollHint: 'Scrollujte',
      hookSuffix: ' — pořád ručně?',
      hookCta: 'Zjistit v auditu',
      hookAria: 'Co vám žere čas? Přejít na automatizační audit.',
    },
    services: { kicker: 'Služby', heading: 'Co stavíme' },
    references: {
      kicker: 'Reference',
      heading: 'Co jsme postavili',
      visit: 'Navštívit web',
    },
    aiready: {
      kicker: 'Připraveno na AI',
      heading: 'Weby, kterým rozumí lidi i stroje.',
      body: 'Vyhledávání se stěhuje do AI asistentů. Weby stavíme tak, aby je ChatGPT, Perplexity i Google AI uměly přečíst, pochopit a citovat jako zdroj — a aby byly připravené na agenty, kteří je jednou budou procházet za vás.',
      geo: {
        label: 'GEO — AI vyhledávání',
        desc: 'Aby vás AI asistenti našli a doporučili.',
        points: ['Strukturovaná data schema.org', 'Obsah čitelný i bez JavaScriptu', 'Copy psané pro citace v AI odpovědích'],
      },
      a2a: {
        label: 'A2A — AI agenti',
        desc: 'Aby s vaším webem uměli pracovat i agenti.',
        points: ['llms.txt & otevřený přístup pro AI crawlery', 'Strojově čitelná struktura a API', 'Volitelně MCP rozhraní pro agenty'],
      },
      note: 'Tenhle web to všechno má. Zkuste se na HALF zeptat svojí AI.',
    },
    about: {
      kicker: 'Studio',
      heading: 'Polovina je váš nápad.',
      body: 'HALF je software studio. Stavíme digitální produkty end-to-end — návrh, vývoj, nasazení, provoz. Malý tým bez mezivrstev: mluvíte přímo s lidmi, kteří váš produkt píší. Polovina je váš nápad. My jsme ta druhá — kód, design a dotažení do konce.',
    },
    cta: {
      demo: {
        kicker: 'Než něco podepíšete',
        heading: 'Uvidíte to fungovat dřív, než nám uvěříte na slovo.',
        body: 'Postavíme vám klikací demo s testovacími daty — zdarma. Ne wireframe, ne prezentaci: produkt, který si osaháte. Bez faktury, bez závazku.',
        cta: 'Chci free demo',
        mailSubject: 'Free demo — mám nápad',
      },
      wizard: {
        kicker: 'AI mapa automatizací',
        heading: 'Co vám žere čas?',
        intro: 'Tři kroky, do 90 sekund, žádné psaní. Řeknete nám, jak běžně fungujete — my ukážeme, co za vás může dělat software, a kolik hodin týdně to vrátí.',
        steps: ['Kontext', 'Rutina', 'Mapa'],
        stepLabel: 'Krok',
        industryPrompt: 'V ČEM PODNIKÁTE?',
        teamPrompt: 'KOLIK VÁS JE?',
        symptomsPrompt: 'CO U VÁS LIDÉ DĚLAJÍ RUČNĚ POŘÁD DOKOLA?',
        symptomsHint: 'Klidně vyberte víc věcí — čím víc toho víme, tím přesnější mapa bude.',
        freqPrompt: 'ZABERE VÁM KONEC MĚSÍCE NEBO REPORTING VÍC NEŽ PÁR HODIN?',
        notePrompt: 'BĚŽNÉ DOPOLEDNE U VÁS VE FIRMĚ?',
        noteHint: 'Nepovinné — ale pár vět vlastními slovy nám řekne nejvíc.',
        notePlaceholder: 'Např.: Ráno projedeme e-maily s objednávkami, přepíšeme je do systému, pak se chystají nabídky…',
        back: 'Zpět',
        next: 'Pokračovat',
        nextHint: 'Vyberte obor a velikost týmu.',
        generate: 'Sestavit mapu',
        analyzing: 'sestavuji mapu…',
        resultPrompt: 'VAŠE MAPA AUTOMATIZACÍ',
        totalLabel: 'zpět každý týden',
        hoursUnit: 'h/týden',
        tags: { quick: '⚡ rychlá výhra', project: '🔧 projekt' },
        lockedNote: 'Další návrhy najdete v plném reportu.',
        emailPrompt: 'Plný report s odhadem úspor vám pošleme na e-mail.',
        emailLabel: 'Váš e-mail',
        emailPlaceholder: 'jmeno@firma.cz',
        phoneLabel: 'Telefon (nepovinné)',
        companyLabel: 'Název firmy (nepovinné)',
        send: 'Chci plný report',
        sendHint: 'Otevře se e-mail s vašimi odpověďmi — nic se nikam neukládá. Report vám pošleme do 24 hodin.',
        sent: 'Díky! Jakmile e-mail odešlete, plný report vám přijde do 24 hodin.',
        call: 'Nezávazný 15min hovor',
        callSubject: 'Nezávazný 15min hovor',
        mailSubject: 'AI mapa automatizací — chci plný report',
        restart: 'Začít znovu',
      },
    },
    process: {
      kicker: 'Jak to probíhá',
      heading: 'Od nápadu k provozu.',
      steps: [
        { index: '01', name: 'Konzultace', body: 'Zavoláme si nebo napíšete. Řeknete nám, co vás pálí; my řekneme, co s tím umíme. Do 24 hodin víte, na čem jste.' },
        { index: '02', name: 'Demo zdarma', body: 'Postavíme klikací prototyp s testovacími daty. Osaháte si produkt dřív, než podepíšete cokoliv.' },
        { index: '03', name: 'Vývoj', body: 'Krátké iterace, průběžné ukázky. Každý týden vidíte, jak produkt roste — žádné černé skříňky.' },
        { index: '04', name: 'Provoz', body: 'Nasadíme, hlídáme, rozvíjíme. Produkt žije dál — a my s ním.' },
      ],
    },
    contact: {
      kicker: 'Kontakt',
      heading: 'Spojme se',
      body: 'Máte nápad nebo projekt? Napište nám — do 24 hodin se ozveme.',
      email: 'solutions.half@gmail.com',
      cta: 'Napsat e-mail',
    },
    footer: { line: '© 2026 HALF — software studio' },
  },
  en: {
    meta: {
      title: 'HALF — Software studio | Web, apps, AI',
      description: 'We build websites, web & mobile apps, APIs, desktop software, AI integrations and automation. Websites built for AI search. The other half of your idea.',
    },
    nav: { services: 'Services', references: 'Work', about: 'Studio', demo: 'Free demo', contact: 'Contact', lang: 'CS', langHref: '/' },
    hero: {
      kicker: 'Software studio',
      headline: 'The other half of your idea.',
      sub: 'Websites, apps and AI integration. From first call to production.',
      scrollHint: 'Scroll',
      hookSuffix: ' — still done by hand?',
      hookCta: 'See it in the audit',
      hookAria: 'What eats your time? Jump to the automation audit.',
    },
    services: { kicker: 'Services', heading: 'What we build' },
    references: {
      kicker: 'Work',
      heading: 'What we built',
      visit: 'Visit site',
    },
    aiready: {
      kicker: 'Built for AI',
      heading: 'Websites that machines can read too.',
      body: 'Search is moving into AI assistants. We build websites that ChatGPT, Perplexity and Google AI can read, understand and cite as a source — ready for the agents that will one day browse them on your behalf.',
      geo: {
        label: 'GEO — AI search',
        desc: 'So AI assistants find and recommend you.',
        points: ['Structured data (schema.org)', 'Content readable without JavaScript', 'Copy written to be cited in AI answers'],
      },
      a2a: {
        label: 'A2A — AI agents',
        desc: 'So agents can work with your site too.',
        points: ['llms.txt & open access for AI crawlers', 'Machine-readable structure and APIs', 'Optional MCP endpoint for agents'],
      },
      note: 'This site has all of it. Try asking your AI about HALF.',
    },
    about: {
      kicker: 'Studio',
      heading: 'One half is your idea.',
      body: 'HALF is a software studio. We build digital products end-to-end — design, development, deployment, operations. A small team with no middle layers: you talk directly to the people writing your product. One half is your idea. We are the other — code, design, and follow-through.',
    },
    cta: {
      demo: {
        kicker: 'Before you sign anything',
        heading: "You'll see it working before you have to trust us.",
        body: "We'll build you a clickable demo with test data — for free. Not a wireframe, not a slide deck: a product you can click through yourself. No invoice, no commitment.",
        cta: 'I want a free demo',
        mailSubject: 'Free demo — I have an idea',
      },
      wizard: {
        kicker: 'AI automation map',
        heading: 'What eats your time?',
        intro: "Three steps, under 90 seconds, no typing needed. Tell us how you normally operate — we'll show what software could take over, and how many hours a week it returns.",
        steps: ['Context', 'Routine', 'Map'],
        stepLabel: 'Step',
        industryPrompt: 'WHAT BUSINESS ARE YOU IN?',
        teamPrompt: 'HOW MANY OF YOU ARE THERE?',
        symptomsPrompt: 'WHAT DO YOUR PEOPLE KEEP DOING BY HAND?',
        symptomsHint: 'Pick as many as you like — the more we know, the sharper the map.',
        freqPrompt: 'DOES MONTH-END OR REGULAR REPORTING TAKE MORE THAN A FEW HOURS?',
        notePrompt: 'A TYPICAL MORNING AT YOUR COMPANY?',
        noteHint: 'Optional — but a few sentences in your own words tell us the most.',
        notePlaceholder: 'E.g.: Mornings we go through order e-mails, retype them into the system, then quotes get prepared…',
        back: 'Back',
        next: 'Continue',
        nextHint: 'Pick your industry and team size.',
        generate: 'Build my map',
        analyzing: 'building your map…',
        resultPrompt: 'YOUR AUTOMATION MAP',
        totalLabel: 'back every week',
        hoursUnit: 'h/week',
        tags: { quick: '⚡ quick win', project: '🔧 project' },
        lockedNote: 'More suggestions are in the full report.',
        emailPrompt: "We'll send the full report with savings estimates to your e-mail.",
        emailLabel: 'Your e-mail',
        emailPlaceholder: 'name@company.com',
        phoneLabel: 'Phone (optional)',
        companyLabel: 'Company name (optional)',
        send: 'Send me the full report',
        sendHint: 'Opens an e-mail with your answers — nothing is stored anywhere. The report arrives within 24 hours.',
        sent: "Thanks! Once you send the e-mail, the full report arrives within 24 hours.",
        call: 'A no-strings 15min call',
        callSubject: 'A no-strings 15min call',
        mailSubject: 'AI automation map — send me the full report',
        restart: 'Start over',
      },
    },
    process: {
      kicker: 'How it works',
      heading: 'From idea to production.',
      steps: [
        { index: '01', name: 'First call', body: "Call or write. Tell us what hurts; we'll tell you what we can do about it. You'll know where you stand within 24 hours." },
        { index: '02', name: 'Free demo', body: 'We build a clickable prototype with test data. Touch the product before you sign anything.' },
        { index: '03', name: 'Build', body: 'Short iterations, regular previews. You watch the product grow every week — no black boxes.' },
        { index: '04', name: 'Run', body: 'We deploy, monitor and keep improving. The product keeps living — and we stay with it.' },
      ],
    },
    contact: {
      kicker: 'Contact',
      heading: "Let's talk",
      body: 'Got an idea or a project? Write to us — we reply within 24 hours.',
      email: 'solutions.half@gmail.com',
      cta: 'Send an email',
    },
    footer: { line: '© 2026 HALF — software studio' },
  },
} satisfies Record<Lang, unknown>
